### ISSUE TITLE
ChIPQC makes a neverending loop while using all chromosomes

### ISSUE THREAD

**Issue by LMannarino** [shengqh/ChIPQC#1]
Hi,
 thank you for fixing the error 

> "names' attribute [9] must be the same length as the vector [7]"

I have installed your fork project and while running ChIPQC on all chromosomes it seems to enter a loop, since it finishes the computation on chromosome Y and begins again from chromosome 1.

I do not know if this should be reported directly to the ChIPQC's author. If so, I apologize.

Thanks
Laura

**Comment by shengqh** [comment]
Hi, Laura:

I didn't touch other part of the code. So if there is another issue, you may need to contact authors directly.

best,

Tiger

**Comment by LMannarino** [comment]
Yes sure,
many thanks!

Laura
